version: '3'
services:
  web:
    image: crccheck/hello-world
    ports:
      - "3000:8000"

  nginx:
    image: yatlab-nginx
    build: .
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - web
