version: 2
jobs:
  deploy:
    docker:
      - image: docker:latest
    environment:
      - IMAGE_NAME: "anilredshift/yatlab-nginx"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t app .
      - run: docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
      - run: docker tag app "${IMAGE_NAME}:${CIRCLE_SHA1}"
      - run: docker tag app "${IMAGE_NAME}:latest"
      - run: docker push "${IMAGE_NAME}:${CIRCLE_SHA1}"
      - run: docker push "${IMAGE_NAME}:latest"


workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
